server:
  port: 2000
eureka:
  server:
    response-cache-update-interval-ms: 1000    
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
    registerWithEureka: false
    fetchRegistry: false
    
spring:
  application:
    name: eureka-server-2000
    

  
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    useDnsForFetchingServiceUrls: true
#    eurekaServerDNSName: eureka.local
#    eurekaServerPort: 8761
#    eurekaServerURLContext: eureka    